package com.example.demo.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Book Entity - Represents a book in the library
 * 
 * SOLID Principles Applied:
 * 
 * 1. Single Responsibility (S):
 *    - ONLY represents Book data model
 *    - No business logic (that's in BookService)
 *    - No HTTP logic (that's in BookController)
 * 
 * 2. Open/Closed (O):
 *    - Can add new fields without modifying existing code
 * 
 * JPA Annotations:
 * @Entity - Marks this as a database table
 * @Table - Specifies table name
 * @Id - Primary key
 * @GeneratedValue - Auto-increment ID
 * @Column - Column configurations
 * 
 * Lombok Annotations:
 * @Data - Generates getters, setters, toString, equals, hashCode
 * @NoArgsConstructor - Generates no-argument constructor (required by JPA)
 * @AllArgsConstructor - Generates all-argument constructor
 */
@Entity
@Table(name = "books")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Book {

    /**
     * Primary Key - Auto-generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * ISBN - International Standard Book Number
     * Unique identifier for books
     * 
     * Example: 978-0134685991
     */
    @Column(nullable = false, unique = true, length = 20)
    @NotBlank(message = "ISBN is required")
    private String isbn;

    /**
     * Book title
     * 
     * Example: "Effective Java"
     */
    @Column(nullable = false)
    @NotBlank(message = "Title is required")
    private String title;

    /**
     * Author name
     * 
     * Example: "Joshua Bloch"
     */
    @Column(nullable = false)
    @NotBlank(message = "Author is required")
    private String author;

    /**
     * Total number of copies library owns
     * 
     * Example: 10
     */
    @Column(nullable = false)
    @Min(value = 0, message = "Total copies must be at least 0")
    private Integer totalCopies;

    /**
     * Number of copies currently available (not borrowed)
     * 
     * Business Rule: availableCopies <= totalCopies
     * 
     * Example: 7 (if 3 are borrowed)
     */
    @Column(nullable = false)
    @Min(value = 0, message = "Available copies must be at least 0")
    private Integer availableCopies;

    /**
     * Timestamp when book was added to database
     * Auto-generated by Hibernate
     */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when book was last updated
     * Auto-updated by Hibernate
     */
    @UpdateTimestamp
    private LocalDateTime updatedAt;

    /**
     * Helper method to check if book is available
     * 
     * @return true if at least one copy available
     */
    public boolean isAvailable() {
        return availableCopies != null && availableCopies > 0;
    }

    /**
     * Helper method to get borrowed count
     * 
     * @return number of borrowed copies
     */
    public int getBorrowedCount() {
        if (totalCopies == null || availableCopies == null) {
            return 0;
        }
        return totalCopies - availableCopies;
    }
}
